<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Display and control one user's bulk generation batch.
 *
 * @package    report_imagealt
 * @copyright  2026 Matt Porritt <matt.porritt@moodle.com>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require(__DIR__ . '/../../config.php');

$id = required_param('id', PARAM_INT);
$action = optional_param('action', '', PARAM_ALPHA);
// A row's own Accept or Discard button names the single suggestion it acts on, and carries no action of its own,
// so which button was pressed is what identifies the action for those. The buttons below the table name the action
// instead and act on whichever rows are ticked.
$acceptid = optional_param('acceptid', 0, PARAM_INT);
$discardid = optional_param('discardid', 0, PARAM_INT);
if ($action === '') {
    $action = $acceptid ? 'accept' : ($discardid ? 'discard' : '');
}
$batch = $DB->get_record('report_imagealt_batch', ['id' => $id], '*', MUST_EXIST);
$context = context::instance_by_id($batch->contextid, MUST_EXIST);
require_login($context->contextlevel === CONTEXT_COURSE ? $context->instanceid : null);
require_capability('report/imagealt:view', $context);
if ((int) $batch->userid !== (int) $USER->id) {
    throw new moodle_exception('nopermissions', 'error');
}
$url = new moodle_url('/report/imagealt/batch.php', ['id' => $id]);
// Set before the actions below rather than with the rest of the page setup further down, because retrying decides
// whether AI can serve the request, which reads provider settings through a form, and a form built with no page
// context raises a developer warning.
$PAGE->set_url($url);
$PAGE->set_context($context);
if ($action !== '') {
    require_sesskey();
    $batchmanager = new \report_imagealt\local\batch_manager();
    $returnurl = $url;
    if ($action === 'cancel') {
        $batchmanager->cancel($id, (int) $USER->id);
    } else if ($action === 'retry') {
        $batchmanager->retry_failed($id, (int) $USER->id);
    } else if ($action === 'accept' || $action === 'discard') {
        $single = $action === 'accept' ? $acceptid : $discardid;
        $selected = $single ? [$single] : optional_param_array('suggestionids', [], PARAM_INT);
        if ($action === 'accept') {
            $result = $batchmanager->accept($id, $selected, (int) $USER->id);
            $notification = get_string('batchacceptresult', 'report_imagealt', $result['accepted']);
            $skippedstring = 'batchacceptskipped';
        } else {
            $result = $batchmanager->discard($id, $selected, (int) $USER->id);
            $notification = get_string('batchdiscardresult', 'report_imagealt', $result['discarded']);
            $skippedstring = 'batchdiscardskipped';
        }
        $notifytype = \core\output\notification::NOTIFY_SUCCESS;
        if ($result['skipped']) {
            $notification .= ' ' . get_string($skippedstring, 'report_imagealt', $result['skipped']);
            $notifytype = \core\output\notification::NOTIFY_WARNING;
        }
        redirect($returnurl, $notification, null, $notifytype);
    }
    redirect($returnurl);
}

$PAGE->set_pagelayout('report');
$PAGE->set_title(get_string('batchtitle', 'report_imagealt'));
$PAGE->set_heading(get_string('batchtitle', 'report_imagealt'));
$PAGE->requires->js_call_amd('report_imagealt/report', 'init');

// The batch's own counters cannot tell a suggestion waiting to be reviewed from one the user has already applied,
// so the summary is given the real breakdown to report.
$statuscounts = array_map('intval', $DB->get_records_sql_menu(
    'SELECT status, COUNT(1) FROM {report_imagealt_suggestion} WHERE batchid = :batchid GROUP BY status',
    ['batchid' => $id],
));
$progress = new \report_imagealt\output\batch_progress($batch, $statuscounts);
// Suggestions are generated by an ad hoc task, so the page has no way to know when the next one lands. While there
// is still work outstanding it reloads itself; once the batch settles it stops, so a finished page stays put.
if ($progress->is_active()) {
    $PAGE->set_periodic_refresh_delay(10);
}

echo $OUTPUT->header();

// The page heading already names the batch, so what is worth saying here is what the page is for: that the work is
// happening in the background, that nothing reaches the images on its own, and how to act on the suggestions.
echo html_writer::tag('p', get_string('batchintro', 'report_imagealt'), ['class' => 'text-muted']);
echo $OUTPUT->render($progress);

$suggestions = $DB->get_records_sql(
    'SELECT suggestion.*, occurrence.itemname, occurrence.previewhash, occurrence.filename, occurrence.src,
            occurrence.alttext
       FROM {report_imagealt_suggestion} suggestion
       JOIN {report_imagealt_occurrence} occurrence ON occurrence.id = suggestion.occurrenceid
      WHERE suggestion.batchid = :batchid
   ORDER BY suggestion.id',
    ['batchid' => $id],
);
// Accepting applies a suggestion exactly as generated, so it is only offered while the suggestion is still the
// unreviewed "ready" one. Everything else is already resolved, or has nothing to apply.
$acceptable = array_filter($suggestions, static fn(stdClass $row): bool => $row->status === 'ready');

$table = new html_table();
// The columns an image is identified by are in the same order as the main report (preview, source, then its
// current alternative text and content item), so moving between the two does not mean relearning the table. The
// AI suggestion sits directly beside the current alternative text, which is the comparison being made here.
$table->head = [
    $acceptable ? $OUTPUT->render(new core\output\checkbox_toggleall('report-imagealt-batch', true, [
        'id' => 'report-imagealt-selectall',
        'label' => get_string('selectall'),
        'labelclasses' => 'visually-hidden',
    ])) : '',
    get_string('imagepreview', 'report_imagealt'),
    get_string('imagesource', 'report_imagealt'),
    get_string('currentalttext', 'report_imagealt'),
    get_string('aisuggestedtext', 'report_imagealt'),
    get_string('suggestionstatus', 'report_imagealt'),
    get_string('contentitem', 'report_imagealt'),
    get_string('actions'),
];
// The same table classes the main report renders with, so the two look like the same report rather than two
// different ones. Set in full rather than appended to, because html_writer::table() only applies its defaults
// when the class is empty, and appending to it silently drops them. Thumbnails make the rows tall, so cell
// content is centred against them rather than sitting at the top of an otherwise empty cell.
$table->attributes['class'] = 'generaltable table table-striped table-hover align-middle';
foreach ($suggestions as $suggestion) {
    if ($suggestion->suggestion && $suggestion->status === 'stale') {
        // Kept visible rather than hidden: an image only goes stale when its own tag changed, which is most often
        // somebody writing alternative text for it by hand, so the description is usually still close to right and
        // worth reading. It is muted and explained so that it does not read as one still waiting to be applied,
        // which is the only thing distinguishing this row from an actionable one apart from its missing buttons.
        $outcome = html_writer::span(s($suggestion->suggestion), 'text-muted')
            . html_writer::div(get_string('batchsuggestionstale', 'report_imagealt'), 'text-muted small mt-1');
    } else if ($suggestion->suggestion) {
        $outcome = s($suggestion->suggestion);
    } else if ($suggestion->errormessage) {
        // Distinguished from a real suggestion, which the plain text of both in one column previously did not.
        $outcome = html_writer::span(s($suggestion->errormessage), 'text-danger');
    } else {
        $outcome = html_writer::span(get_string('batchnosuggestionyet', 'report_imagealt'), 'text-muted');
    }

    // A thumbnail anchors each row to the actual image far better than the name of the content it sits in, which
    // is often the same for several rows.
    $preview = \report_imagealt\output\preview::thumbnail(
        (int) $suggestion->occurrenceid,
        $suggestion->previewhash,
        '',
        $suggestion->src,
    );
    $sourcelabel = (string) ($suggestion->filename ?: $suggestion->src);
    $source = \report_imagealt\output\preview::source_link(
        (int) $suggestion->occurrenceid,
        $suggestion->previewhash,
        $sourcelabel,
        $suggestion->src,
    );

    $rowactions = '';
    $select = '';
    if ($suggestion->status === 'ready') {
        $select = $OUTPUT->render(new core\output\checkbox_toggleall('report-imagealt-batch', false, [
            'id' => "report-imagealt-select-{$suggestion->id}",
            'name' => 'suggestionids[]',
            'value' => $suggestion->id,
            'label' => get_string('selectitem', 'moodle', s($sourcelabel)),
            'labelclasses' => 'visually-hidden',
        ]));
        // Applies the suggestion exactly as written, for the common case where it needs no changes. Opening the
        // modal to read an unchanged description and press Save is friction this avoids.
        $acceptlabel = get_string('batchaccept', 'report_imagealt');
        $rowactions .= html_writer::tag('button', $OUTPUT->pix_icon('t/check', ''), [
            'type' => 'submit',
            'name' => 'acceptid',
            'value' => $suggestion->id,
            'class' => 'btn btn-icon',
            'title' => $acceptlabel,
            'aria-label' => $acceptlabel,
        ]);
        // Rejecting has to be as direct as accepting, or the only cheap way to clear a suggestion the reviewer
        // disagrees with is to accept it. No confirmation step: nothing has been written to the image, and the
        // image can be sent for generation again afterwards.
        $discardlabel = get_string('batchdiscard', 'report_imagealt');
        $rowactions .= html_writer::tag('button', $OUTPUT->pix_icon('t/delete', ''), [
            'type' => 'submit',
            'name' => 'discardid',
            'value' => $suggestion->id,
            'class' => 'btn btn-icon',
            'title' => $discardlabel,
            'aria-label' => $discardlabel,
        ]);
    }
    $rowactions .= \report_imagealt\output\actions::edit_button(
        (int) $suggestion->occurrenceid,
        (int) $context->id,
    );

    $table->data[] = [
        $select,
        $preview,
        $source,
        trim((string) $suggestion->alttext) === ''
            ? get_string('unknownvalue', 'core_ai')
            : s($suggestion->alttext),
        $outcome,
        // Already on this suggestion's batch page, so the badge is not linked back to it.
        \report_imagealt\output\suggestion_state::badge($suggestion->status),
        s($suggestion->itemname),
        html_writer::div($rowactions, 'd-flex gap-1'),
    ];
}
if ($table->data) {
    // The table is posted back to this page: per row buttons name their own suggestion, and the buttons below act
    // on every ticked row in one go.
    echo html_writer::start_tag('form', [
        'method' => 'post',
        'action' => $url->out(false),
        'id' => 'report-imagealt-batch-form',
    ]);
    echo html_writer::empty_tag('input', ['type' => 'hidden', 'name' => 'sesskey', 'value' => sesskey()]);
    // Narrow viewports scroll the table sideways rather than having its columns clipped at the page edge.
    echo html_writer::div(html_writer::table($table), 'table-responsive');
    if ($acceptable) {
        // Positioned like the report's own bulk button: below its table and left aligned, separate from the page
        // level actions on the right. Rendered disabled and registered as core/checkbox-toggleall action elements
        // for this toggle group, so core enables them as soon as a row is ticked and disables them again at zero.
        // Discarding is the secondary of the two, but sits beside Accept rather than being hidden away, so working
        // through a batch does not push the reviewer towards accepting whatever they are given.
        //
        // Outline rather than filled, matching the report's own bulk button, which spends most of its life disabled
        // for the same reason these do. A disabled filled button keeps most of its colour and still reads as
        // something worth pressing; an outline one visibly loses its fill.
        $bulkactions = html_writer::tag('button', get_string('batchacceptselected', 'report_imagealt'), [
            'type' => 'submit',
            'name' => 'action',
            'value' => 'accept',
            'class' => 'btn btn-outline-primary',
            'disabled' => 'disabled',
            'data-action' => 'toggle',
            'data-toggle' => 'action',
            'data-togglegroup' => 'report-imagealt-batch',
        ]);
        $bulkactions .= html_writer::tag('button', get_string('batchdiscardselected', 'report_imagealt'), [
            'type' => 'submit',
            'name' => 'action',
            'value' => 'discard',
            'class' => 'btn btn-outline-secondary',
            'disabled' => 'disabled',
            'data-action' => 'toggle',
            'data-toggle' => 'action',
            'data-togglegroup' => 'report-imagealt-batch',
        ]);
        echo html_writer::div($bulkactions, 'd-flex gap-2 mt-3');
    }
    echo html_writer::end_tag('form');
} else {
    // A batch is never created without eligible images, so this only shows if its images were removed afterwards.
    // Rendering bare column headings with nothing under them would leave the user with no idea why.
    echo $OUTPUT->notification(get_string('batchnoitems', 'report_imagealt'), 'info', false);
}

// Actions sit below the table they act on, aligned right, rather than above it where "Cancel" read as though it
// applied to the page as a whole.
$actions = $OUTPUT->single_button(
    new moodle_url('/report/imagealt/index.php', ['contextid' => $context->id]),
    get_string('backtoreport', 'report_imagealt'),
    'get',
);
if ($batch->failed) {
    $actions .= $OUTPUT->single_button(
        new moodle_url($url, ['action' => 'retry', 'sesskey' => sesskey()]),
        get_string('retryfailed', 'report_imagealt'),
        'post',
    );
}
if ($progress->is_active()) {
    // No confirmation step: cancelling only skips images that have not been processed yet, keeps every suggestion
    // already generated, and can be undone by generating for those images again.
    $actions .= $OUTPUT->render(new single_button(
        new moodle_url($url, ['action' => 'cancel', 'sesskey' => sesskey()]),
        get_string('batchcancel', 'report_imagealt'),
        'post',
        single_button::BUTTON_DANGER,
    ));
}
echo html_writer::div($actions, 'd-flex justify-content-end gap-2 mt-3');

echo $OUTPUT->footer();
