@editor @editor_tiny @tiny_aiplacement @javascript @_file_upload @accessibility
Feature: Generate alternative text for images using AI
  In order to make authored images accessible
  As a content author
  I need AI assistance in the existing image details dialog

  Background:
    Given the following "courses" exist:
      | fullname | shortname | format |
      | Course 1 | C1        | topics |
    And the following "activities" exist:
      | activity | name   | course | content | contentformat |
      | page     | Page 1 | C1     | Content | 1             |
    And the following "core_ai > ai providers" exist:
      | provider          | name   | enabled | apikey | orgid |
      | aiprovider_openai | openai | 1       | 123    | abc   |
    And I set the following action configuration for ai provider with name "openai":
      | action         | enabled |
      | describe_image | 1       |
    And the following config values are set as admin:
      | enabled        | 1 | aiplacement_editor |
      | describe_image | 1 | aiplacement_editor |
    And I enable "editor" "aiplacement" plugin

  Scenario: Generate and review alt text for a new image
    Given I am on the "Page 1" "page activity editing" page logged in as admin
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And ".modal-dialog.modal-xl:not(.modal-lg)" "css_element" should exist
    And I click on "Browse repositories" "button" in the "Insert image" "dialogue"
    And I upload "lib/editor/tiny/tests/behat/fixtures/moodle-logo.png" to the file picker for TinyMCE
    And I mock the image description response as "success"
    And I wait until "Generate alt text with AI" "button" exists
    And ".modal-dialog.modal-xl:not(.modal-lg)" "css_element" should exist
    And "[data-action='generate-alt-text'].btn-outline-primary:not(.btn-sm)" "css_element" should exist
    And "[data-action='generate-alt-text'] .tiny-aiplacement-sparkles-icon" "css_element" should exist
    When I click on "Generate alt text with AI" "button" in the "Image details" "dialogue"
    And I should see "Welcome to the new AI feature!" in the "AI usage policy" "dialogue"
    And I click on "Accept and continue" "button" in the "AI usage policy" "dialogue"
    Then I wait until "Review the AI-generated description for accuracy before saving." "text" exists
    And the field "How would you describe this image to someone who cannot see it?" matches value "A Moodle logo. - Generated by AI"
    And "Regenerate" "button" should exist in the "Image details" "dialogue"
    And the "Image details" "dialogue" should meet accessibility standards

  Scenario: Existing alt text is not replaced without confirmation
    Given I am on the "Page 1" "page activity editing" page logged in as admin
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And I click on "Browse repositories" "button" in the "Insert image" "dialogue"
    And I upload "lib/editor/tiny/tests/behat/fixtures/moodle-logo.png" to the file picker for TinyMCE
    And I set the field "How would you describe this image to someone who cannot see it?" to "My description"
    And I wait until "Replace with AI suggestion" "button" exists
    When I click on "Replace with AI suggestion" "button" in the "Image details" "dialogue"
    Then I wait until "This replaces the description you’ve already written. This can’t be undone." "text" exists
    And I click on "Keep mine" "button" in the "Image details" "dialogue"
    And the field "How would you describe this image to someone who cannot see it?" matches value "My description"

  Scenario: Generate replacement alt text for an already embedded image
    Given I am on the "Page 1" "page activity editing" page logged in as admin
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And I click on "Browse repositories" "button" in the "Insert image" "dialogue"
    And I upload "lib/editor/tiny/tests/behat/fixtures/moodle-logo.png" to the file picker for TinyMCE
    And I set the field "How would you describe this image to someone who cannot see it?" to "Existing description"
    And I click on "Save" "button" in the "Image details" "dialogue"
    And I select the "img" element in position "0" of the "Page content" TinyMCE editor
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And I mock the image description response as "success"
    And I wait until "Replace with AI suggestion" "button" exists
    When I click on "Replace with AI suggestion" "button" in the "Image details" "dialogue"
    And I click on "Replace" "button" in the "Image details" "dialogue"
    And I click on "Accept and continue" "button" in the "AI usage policy" "dialogue"
    Then I wait until "Review the AI-generated description for accuracy before saving." "text" exists
    And the field "How would you describe this image to someone who cannot see it?" matches value "A Moodle logo. - Generated by AI"

  Scenario: A failed request keeps manual entry available
    Given I am on the "Page 1" "page activity editing" page logged in as admin
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And I click on "Browse repositories" "button" in the "Insert image" "dialogue"
    And I upload "lib/editor/tiny/tests/behat/fixtures/moodle-logo.png" to the file picker for TinyMCE
    And I mock the image description response as "failure"
    And I wait until "Generate alt text with AI" "button" exists
    When I click on "Generate alt text with AI" "button" in the "Image details" "dialogue"
    And I click on "Accept and continue" "button" in the "AI usage policy" "dialogue"
    Then I wait until "The image description could not be generated." "text" exists
    And "Try again" "button" should exist in the "Image details" "dialogue"
    And I set the field "How would you describe this image to someone who cannot see it?" to "Manual description"
    And the field "How would you describe this image to someone who cannot see it?" matches value "Manual description"

  Scenario: A pending request can be cancelled
    Given I am on the "Page 1" "page activity editing" page logged in as admin
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And I click on "Browse repositories" "button" in the "Insert image" "dialogue"
    And I upload "lib/editor/tiny/tests/behat/fixtures/moodle-logo.png" to the file picker for TinyMCE
    And I mock the image description response as "pending"
    And I wait until "Generate alt text with AI" "button" exists
    When I click on "Generate alt text with AI" "button" in the "Image details" "dialogue"
    And I click on "Accept and continue" "button" in the "AI usage policy" "dialogue"
    Then I wait for the image description generation to be pending
    And "[data-action='cancel-alt-text']" "css_element" should exist in the ".alert.alert-info" "css_element"
    And I click on "Cancel" "button" in the "Image details" "dialogue"
    And I wait until "Generate alt text with AI" "button" exists

  Scenario: The affordance is hidden when no eligible provider is available
    Given I set the following action configuration for ai provider with name "openai":
      | action         | enabled |
      | describe_image | 0       |
    When I am on the "Page 1" "page activity editing" page logged in as admin
    And I click on the "Image" button for the "Page content" TinyMCE editor
    And I click on "Browse repositories" "button" in the "Insert image" "dialogue"
    And I upload "lib/editor/tiny/tests/behat/fixtures/moodle-logo.png" to the file picker for TinyMCE
    Then "Generate alt text with AI" "button" should not exist in the "Image details" "dialogue"
    And "How would you describe this image to someone who cannot see it?" "field" should exist
    And "Decorative image" "field" should exist
